# Base image
FROM node:18

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package.json ./
RUN npm install

# Bundle app source
COPY prisma ./prisma
COPY src ./src
COPY tsconfig.json ./
COPY package.json ./
COPY index.ts ./

# Generate the client
RUN npx prisma generate

# Build the client
RUN npm run build
RUN npm run cosmo

# RUN cp -r ./graphql ./dist

# Expose the port that the server will run on
EXPOSE 80

# Start the server
CMD [ "npm", "run", "start:prod" ]

